on:
  push:
    branches:
      - main # Push events on main branch
permissions:
  contents: read
  actions: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.12.1"
      - name: Install ubuntu deps
        if: contains(matrix.os, 'ubuntu-20.04')
        run: sudo apt install mesa-common-dev libglu1-mesa-dev libegl1 libopengl-dev
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install deps
        run: pnpm i --frozen-lockfile
      - name: Build Vixen
        run: pnpm build
      - name: Archive using pnpm pack
        run: pnpm pack
      - uses: actions/upload-artifact@v4
        with:
          name: latest-release
          path: vixen-js-core-latest-main.tgz
      - uses: vixen-js/action-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          code: latest-main
          name: Latest main Release
          body: >
            Latest auto release corresponding to commit ${{github.sha}} ðŸ”¥.
            To install do:
            `pnpm i https://github.com/Vixen-js/core/releases/download/latest-main/core-main.tgz`
          assets: >
            vixen-js-core-latest-main.tgz:vixen-js-main.tgz:application/tar+gzip
          recreate: true
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Vixen-js/core
          event-type: on-demand-build
          client-payload: '{"ref": "${{ github.ref }}","tag": "latest-main"}'
